### ISSUE TITLE
GPS isn't work

### ISSUE THREAD

**Issue by Aurusd** [intel-aero/meta-intel-aero#269]
No signal from GPS
![clip2net_170819174853](https://user-images.githubusercontent.com/10154188/29487717-c6ee521a-8506-11e7-92d0-ca8bd24b5e30.png)
GPS is turned up, and wire is connected, but there isnt any satellite.
How can resolve it or at least test what is caused this?
OS version:1.5.1
no gps lock for vehicle on qGroundControl

**Comment by anselmolsm** [comment]
Just checking, have you tried that outdoors?

**Comment by Aurusd** [comment]
yes i have tried outdoor, but there is no signal gps

**Comment by guermonprez** [comment]
@anselmolsm what would be the best way to debug this problem? do we have more logs?
if QGC says the link with the drone is ok, I guess there is no way the GPS messages would be lost in the middle?
so next step would be to test far from buildings?
what do you think?

**Comment by anselmolsm** [comment]
My question about testing outdoors was because I've seen GPS issues related to interference indoors in the past.
@lucasdemarchi @zehortigoza any suggestion regarding logs?

**Comment by zehortigoza** [comment]
What is the PX4 version and the FPGA version?

To get the PX4 version:
Go to the icon with the paper and a magnifier(the 5th from the left) then go to Mavlink Console and type: ver all
please paste the output here

To get the FPGA version:
Go to Aero board terminal(by SSH or with monitor and keyboard) and type: aero-get-version.py

Why I'm asking this is because newer PX4 firmwares(including the one in the 1.5v image) needs the new FPGA firwmare. If your FPGA firmware is 0xC0 you need to update it, and if not update the problem will be exactly the one that you are having.

**Comment by VineeshKK** [comment]
You can  quickly check if GPS coordinates are received by FC.
1.	SSH to Aero shell.
2.	Copy the _mavlink_shell.py_ to _/home/root_
a.	You can find **mavlink_shell.py**  here at https://github.com/PX4/Firmware/tree/master/Tools

3.	Then login into FC shell( nsh>) using the following command
a.	**./mavlink_shell.py 0.0.0.0:14550**
4.	Run the FC shell command:  **listener vehicle_gps_position** 

 It will show lat: lon: and other GPS parameters like hdop, vdop..etc.

**Comment by Aurusd** [comment]
ver all
![clip2net_170904095412](https://user-images.githubusercontent.com/10154188/30014853-0b4a95fc-9157-11e7-88b2-cbc756e78dc4.png)

**Comment by VineeshKK** [comment]
@Aurusd  Are you able to get GPS Coordinates from NutShell?

**Comment by zehortigoza** [comment]
@Aurusd What about the FPGA version? With this PX4 firmware version you need the FPGA firmware with version 0xC1.

**Comment by Aurusd** [comment]
oh.. sorry your advise is right and now gps works! Thanks!
