### ISSUE TITLE
Problem with librealsense config files (and binaries) not getting installed

### ISSUE THREAD

**Issue by mindThomas** [intel-aero/meta-intel-aero#62]
While trying to sort out all the librealsense mess I simply can't get my head around the missing parts from the librealsense library build.
I have managed to successfully build the image (obs. without build errors) while using librealsense 1.12.0 within the librealsense meta layer and realsense-camera in the ROS layer pointing/using this version.

But when I boot the image it does not boot properly but it detects the camera.
Though after detecting the camera I get an error that it does not find: "/usr/local/bin/usb-R200-in_udev"
This seem to be a part of the librealsense build which should have been copied from the config folder, see: https://github.com/IntelRealSense/librealsense/blob/master/scripts/install-r200-udev-fix.sh

What am I missing in my bb files to get this installed and become a part of the image as well?

PS. With regard to the realsense-camera layer, can anyone explain why this does not get included in the image automatically but always have to be built seperately as a package afterwards ("bitbake realsense-camera")?

**Comment by mbelluzzo** [comment]
If "realsense-camera" isn't get included on your image, you probably have a dirty environment. We have to change some layers of the image due to repositories being no longer maintained. When dealing with yocto layers and repo manifest, during development is impossible to keep everything working on every commit due to circular dependency: manifest revision depends on rev number for a meta layer that needs manifest being updated to work correctly as well. So I do suggest to use our releases and release candidates since those are guarantee to be at least building correctly on a correctly set environment.
